# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'se1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for se1

  target 'se1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'se1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'share' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for share
  pod 'Toast', '~> 4.0.0'

end
